### ISSUE TITLE
Setup for Hallowed Sepulcher 

### ISSUE THREAD

**Issue by Nick2bad4u** [t8or/runelite-recommended-equipment#6]
Optimal Hallowed Sepuchler setup:
![image](https://github.com/user-attachments/assets/93869014-be76-4b32-891e-4f7fc1548d36)

I'n not sure what data you need so Ill include a layout and tags.

`banktags,1,hallowed,24719,8794,8782,8880,561,13128,564,27509,21282,24946,21073,21076,21070,21061,21067,10890,22932,995,13280,3325,24133,12625,12627,4824,4699,24740,24738,24731,24733,24729,24725,24727,24721,24723,24719,24711,24709,12791,24761,24758,24755,24752,24749,24743,24478`

`banktaglayoutsplugin:hallowed,21282:64,24743:1,24133:65,24719:4,24719:5,24740:69,24719:6,3325:7,13280:8,24725:9,24721:10,3325:12,3325:13,8782:14,8782:15,8880:16,24749:17,24723:18,8782:20,8782:21,12791:88,24752:25,24755:32,24758:33,24731:34,13128:39,22932:103,564:40,561:41,4699:42,995:106,24946:107,24478:44,24709:108,24733:109,24738:45,24729:110,27509:46,24727:47,24711:111,12627:52,10890:53,8794:54,4824:55,12625:56,24719:125,3325:126,8782:127,banktag:hallowed,24719,8794,8782,8880,561,13128,564,27509,21282,24946,21073,21076,21070,21061,21067,10890,22932,995,13280,3325,24133,12625,12627,4824,4699,24740,24738,24731,24733,24729,24725,24727,24721,24723,24719,24711,24709,12791,24761,24758,24755,24752,24749,24743,24478`

Theres also a setup on the wiki here:
https://oldschool.runescape.wiki/w/Hallowed_Sepulchre#Recommended_setup
But it's missing the rewards.

**Comment by t8or** [comment]
Thank you! I found this page in the wiki: https://oldschool.runescape.wiki/w/Hallowed_Sepulchre/Strategies, which has the supported table for the plugin to read. It should be live in the plugin in the next 5 or so minutes. Feel free to update that table on the wiki to update the plugin further!

**Comment by Nick2bad4u** [comment]
> Thank you! I found this page in the wiki: [oldschool.runescape.wiki/w/Hallowed_Sepulchre/Strategies](https://oldschool.runescape.wiki/w/Hallowed_Sepulchre/Strategies), which has the supported table for the plugin to read. It should be live in the plugin in the next 5 or so minutes. Feel free to update that table on the wiki to update the plugin further!

Great thank you! I figured it would be better than my manual setup ;)
