### ISSUE TITLE
Fight Cave

### ISSUE THREAD

**Issue by BeeZZy03** [t8or/runelite-recommended-equipment#9]
Lets get some armor setups for fight cave, ranged, void, guthans, pure, melee, tank, magic, and iron

**Comment by adamk33n3r** [comment]
Fight caves strategies already exist, is there something missing? If so, edit the wiki.

**Comment by t8or** [comment]
@BeeZZy03 We do have the existing Fight Caves setups in the plugin - it can be found under Jad's name, though you bring up a good point. It should probably be called Fight Caves...
